export const mockPartners = [
  {
    id: 'EMP-001',
    name: 'Klinikum Düsseldorf GmbH',
    type: 'Employers',
    status: 'Active',
    manager: 'Lea Hoffmann',
    employees: 84,
    revenue: 70560,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'HR Mobility Desk',
    contactRole: 'Talent Operations',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-002',
    name: 'Alloheim Senioren-Residenzen',
    type: 'Employers',
    status: 'Active',
    manager: 'Lea Hoffmann',
    employees: 61,
    revenue: 51240,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'Regional HR Lead',
    contactRole: 'Workforce Mobility',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-003',
    name: 'AHO Germany (International Healthcare)',
    type: 'Employers',
    status: 'Active',
    manager: 'Jonas Reuter',
    employees: 73,
    revenue: 61320,
    city: 'Cologne',
    partnerCount: 1,
    contactName: 'Medical Talent Team',
    contactRole: 'International Staffing',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-004',
    name: 'Siemens Healthineers AG',
    type: 'Employers',
    status: 'Active',
    manager: 'Jonas Reuter',
    employees: 52,
    revenue: 43680,
    city: 'Erlangen/NRW',
    partnerCount: 1,
    contactName: 'Mobility Programs Office',
    contactRole: 'Global Talent Mobility',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-005',
    name: 'Deutsche Bahn Engineering',
    type: 'Employers',
    status: 'Active',
    manager: 'Mina Farouk',
    employees: 38,
    revenue: 31920,
    city: 'Frankfurt',
    partnerCount: 1,
    contactName: 'Project Talent Desk',
    contactRole: 'Engineering Workforce',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-006',
    name: 'Universitätsklinikum Köln',
    type: 'Employers',
    status: 'Active',
    manager: 'Jonas Reuter',
    employees: 66,
    revenue: 55440,
    city: 'Cologne',
    partnerCount: 1,
    contactName: 'Clinical Recruiting',
    contactRole: 'International Hiring',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-007',
    name: 'Henkel AG & Co. KGaA',
    type: 'Employers',
    status: 'Active',
    manager: 'Lea Hoffmann',
    employees: 29,
    revenue: 24360,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'Talent Acquisition',
    contactRole: 'Corporate Mobility',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-008',
    name: 'Rheinmetall AG',
    type: 'Employers',
    status: 'Active',
    manager: 'Lea Hoffmann',
    employees: 41,
    revenue: 34440,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'Workforce Integration',
    contactRole: 'Industrial Hiring',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-009',
    name: 'Uniklinik RWTH Aachen',
    type: 'Employers',
    status: 'Active',
    manager: 'Mina Farouk',
    employees: 47,
    revenue: 39480,
    city: 'Aachen',
    partnerCount: 1,
    contactName: 'Hospital HR',
    contactRole: 'Medical Recruitment',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-010',
    name: 'Vonovia SE (tech staff)',
    type: 'Employers',
    status: 'Active',
    manager: 'Mina Farouk',
    employees: 23,
    revenue: 19320,
    city: 'Bochum',
    partnerCount: 1,
    contactName: 'Tech Recruiting',
    contactRole: 'Digital Talent',
    agreementStatus: 'Master Housing Agreement - Active',
  },
  {
    id: 'EMP-REST',
    name: '+17 Additional Employer Contracts',
    type: 'Employers',
    status: 'Active',
    manager: 'National Accounts',
    employees: 631,
    revenue: 514440,
    city: 'Multi-city',
    partnerCount: 17,
    isAggregate: true,
    contactName: 'Grouped Employer Portfolio',
    contactRole: 'National Accounts',
    agreementStatus: 'Grouped Portfolio Commitments - Active',
  },
  {
    id: 'AG-001',
    name: 'Hays Germany GmbH',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 34,
    revenue: 14280,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'Placement Desk',
    contactRole: 'Agency Account Lead',
    agreementStatus: 'Referral Service Fee Agreement - Active',
  },
  {
    id: 'AG-002',
    name: 'Randstad Deutschland GmbH',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 28,
    revenue: 11760,
    city: 'Cologne',
    partnerCount: 1,
    contactName: 'Mobility Placements Team',
    contactRole: 'Agency Account Lead',
    agreementStatus: 'Referral Service Fee Agreement - Active',
  },
  {
    id: 'AG-003',
    name: 'Adecco Germany',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 19,
    revenue: 7980,
    city: 'Bonn',
    partnerCount: 1,
    contactName: 'Healthcare Placements',
    contactRole: 'Agency Account Lead',
    agreementStatus: 'Referral Service Fee Agreement - Active',
  },
  {
    id: 'AG-004',
    name: 'Manpower Deutschland',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 14,
    revenue: 5880,
    city: 'Berlin',
    partnerCount: 1,
    contactName: 'Skilled Migration Desk',
    contactRole: 'Agency Account Lead',
    agreementStatus: 'Referral Service Fee Agreement - Active',
  },
  {
    id: 'AG-005',
    name: 'Page Personnel Deutschland',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 11,
    revenue: 4620,
    city: 'Frankfurt',
    partnerCount: 1,
    contactName: 'Tech Placements',
    contactRole: 'Agency Account Lead',
    agreementStatus: 'Referral Service Fee Agreement - Active',
  },
  {
    id: 'AG-REST',
    name: '+7 Additional Agency Contracts',
    type: 'Recruitment Agencies',
    status: 'Active',
    manager: 'Clara Stein',
    employees: 79,
    revenue: 27280,
    city: 'Multi-city',
    partnerCount: 7,
    isAggregate: true,
    contactName: 'Grouped Agency Portfolio',
    contactRole: 'Agency Network',
    agreementStatus: 'Grouped Referral Agreements - Active',
  },
  {
    id: 'UNI-001',
    name: 'Heinrich-Heine-Universität Düsseldorf',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 112,
    revenue: 94080,
    city: 'Düsseldorf',
    partnerCount: 1,
    contactName: 'International Office',
    contactRole: 'Housing Partnerships',
    agreementStatus: 'Semester Housing Agreement - Active',
  },
  {
    id: 'UNI-002',
    name: 'RWTH Aachen University',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 98,
    revenue: 82320,
    city: 'Aachen',
    partnerCount: 1,
    contactName: 'International Student Services',
    contactRole: 'Housing Partnerships',
    agreementStatus: 'Semester Housing Agreement - Active',
  },
  {
    id: 'UNI-003',
    name: 'Universität zu Köln',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 87,
    revenue: 73080,
    city: 'Cologne',
    partnerCount: 1,
    contactName: 'Student Mobility Office',
    contactRole: 'Housing Partnerships',
    agreementStatus: 'Semester Housing Agreement - Active',
  },
  {
    id: 'UNI-004',
    name: 'TH Köln (Technische Hochschule Köln)',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 54,
    revenue: 45360,
    city: 'Cologne',
    partnerCount: 1,
    contactName: 'International Programs',
    contactRole: 'Housing Partnerships',
    agreementStatus: 'Semester Housing Agreement - Active',
  },
  {
    id: 'UNI-005',
    name: 'Universität Bonn',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 71,
    revenue: 59640,
    city: 'Bonn',
    partnerCount: 1,
    contactName: 'Exchange Services',
    contactRole: 'Housing Partnerships',
    agreementStatus: 'Semester Housing Agreement - Active',
  },
  {
    id: 'UNI-REST',
    name: '+3 Additional University Partnerships',
    type: 'Universities',
    status: 'Active',
    manager: 'Eva Lorenz',
    employees: 163,
    revenue: 129520,
    city: 'Multi-city',
    partnerCount: 3,
    isAggregate: true,
    contactName: 'Grouped University Portfolio',
    contactRole: 'Academic Partnerships',
    agreementStatus: 'Grouped Semester Agreements - Active',
  },
];

export const mockReservations = [
  {
    id: 'RES-001',
    partnerId: 'EMP-001',
    roomsReserved: 24,
    roomsFilled: 18,
    status: 'Reserved',
    label: 'Employer pipeline allocation',
    daysRemaining: 34,
    notes: 'Reserved against signed employer commitments ahead of July move-ins.',
  },
  {
    id: 'RES-002',
    partnerId: 'EMP-003',
    roomsReserved: 19,
    roomsFilled: 14,
    status: 'Reserved',
    label: 'Employer pipeline allocation',
    daysRemaining: 28,
    notes: 'Reserved for healthcare hires with housing already confirmed.',
  },
  {
    id: 'RES-003',
    partnerId: 'EMP-006',
    roomsReserved: 17,
    roomsFilled: 13,
    status: 'Reserved',
    label: 'Employer pipeline allocation',
    daysRemaining: 41,
    notes: 'Move-ins spread across Cologne launch cohorts.',
  },
  {
    id: 'RES-004',
    partnerId: 'UNI-001',
    roomsReserved: 14,
    roomsFilled: 10,
    status: 'Reserved',
    label: 'University semester intake',
    daysRemaining: 44,
    notes: 'Autumn semester arrivals held against confirmed student lists.',
  },
  {
    id: 'RES-005',
    partnerId: 'EMP-REST',
    roomsReserved: 13,
    roomsFilled: 8,
    status: 'Reserved',
    label: 'Employer pipeline allocation',
    daysRemaining: 31,
    notes: 'Grouped national accounts capacity held in Wave 2 assets.',
  },
  {
    id: 'RES-006',
    partnerId: 'EMP-REST',
    roomsReserved: 33,
    roomsFilled: 0,
    status: 'Maintenance Buffer',
    label: 'Reserved maintenance buffer',
    daysRemaining: null,
    notes: 'Operational churn and reletting buffer held at the 5% hard cap.',
  },
];


export const mockThreads = [
  {
    id: 'TR-001',
    partnerId: 'EMP-001',
    partnerName: 'Klinikum Düsseldorf GmbH',
    partnerType: 'Employers',
    lastMessage: 'Please hold 6 more rooms for the August nursing intake.',
    timestamp: '2026-05-22T10:30:00Z',
    unreadCount: 0,
    assignedTo: 'Lea Hoffmann',
    messages: [
      { sender: 'HR Mobility Desk', text: 'We have a confirmed August intake of nurses from India and the Philippines.', timestamp: '2026-05-21T14:20:00Z' },
      { sender: 'Lea H. (Arrivio)', text: 'Confirmed. We are holding six rooms in Flingern and two in Oberbilk.', timestamp: '2026-05-21T16:45:00Z' },
      { sender: 'HR Mobility Desk', text: 'Please hold 6 more rooms for the August nursing intake.', timestamp: '2026-05-22T10:30:00Z' },
    ],
  },
  {
    id: 'TR-002',
    partnerId: 'AG-001',
    partnerName: 'Hays Germany GmbH',
    partnerType: 'Recruitment Agencies',
    lastMessage: 'Can you confirm which placements are in the June service fee batch?',
    timestamp: '2026-05-22T09:15:00Z',
    unreadCount: 2,
    assignedTo: 'Clara Stein',
    messages: [
      { sender: 'Placements Team', text: 'We just updated the final move-in list for the June healthcare cohort.', timestamp: '2026-05-21T11:00:00Z' },
      { sender: 'Clara S. (Arrivio)', text: 'Received. We will reconcile against signed leases today.', timestamp: '2026-05-21T13:30:00Z' },
      { sender: 'Placements Team', text: 'Can you confirm which placements are in the June service fee batch?', timestamp: '2026-05-22T09:15:00Z' },
    ],
  },
  {
    id: 'TR-003',
    partnerId: 'UNI-001',
    partnerName: 'Heinrich-Heine-Universität Düsseldorf',
    partnerType: 'Universities',
    lastMessage: 'Orientation week starts on September 2 and housing lists are final.',
    timestamp: '2026-05-21T16:20:00Z',
    unreadCount: 0,
    assignedTo: 'Eva Lorenz',
    messages: [
      { sender: 'International Office', text: 'Will the Düsseldorf apartment allocation be ready before orientation week?', timestamp: '2026-05-20T09:00:00Z' },
      { sender: 'Eva L. (Arrivio)', text: 'Yes, all held rooms are blocked and confirmations have been sent.', timestamp: '2026-05-20T11:45:00Z' },
      { sender: 'International Office', text: 'Orientation week starts on September 2 and housing lists are final.', timestamp: '2026-05-21T16:20:00Z' },
    ],
  },
];

export const mockServiceFees = [
  {
    id: 'SVF-001',
    agency: 'Employer placement fees outstanding',
    tenant: 'Confirmed employer cohorts',
    moveIn: '2026-05-30',
    amount: 74200,
    status: 'Pending',
    dueDate: '2026-06-21',
    category: 'Employers',
  },
  {
    id: 'SVF-002',
    agency: 'Recruitment agency service fees',
    tenant: 'Agency-referred move-ins',
    moveIn: '2026-05-30',
    amount: 31800,
    status: 'Pending',
    dueDate: '2026-06-21',
    category: 'Recruitment Agencies',
  },
  {
    id: 'SVF-003',
    agency: 'University semester invoices',
    tenant: 'Autumn intake housing block',
    moveIn: '2026-05-30',
    amount: 21400,
    status: 'Pending',
    dueDate: '2026-06-21',
    category: 'Universities',
  },
];

export const recentB2BActivity = [
  { id: 1, type: 'capacity', text: 'Reserved 87 rooms against named employer and university commitments.', timestamp: '2026-05-22T10:00:00Z' },
  { id: 2, type: 'housing', text: 'Farah Yildiz assigned to Arrivio Bonn Endenich.', timestamp: '2026-05-22T09:30:00Z' },
  { id: 3, type: 'message', text: 'New message from Hays Germany GmbH on June service fee reconciliation.', timestamp: '2026-05-22T09:15:00Z' },
  { id: 4, type: 'payment', text: 'Pending service fees queue updated to €127,400.', timestamp: '2026-05-21T17:00:00Z' },
  { id: 5, type: 'onboarding', text: 'RWTH Aachen University semester housing list locked for autumn intake.', timestamp: '2026-05-21T16:45:00Z' },
  { id: 6, type: 'capacity', text: 'Maintenance buffer confirmed at 33 rooms across live buildings.', timestamp: '2026-05-21T14:20:00Z' },
];
