// src/mockdata/dashboardData.js

export const dashboardData = {
  metrics: [
    { label: 'Active Tenants', value: '312', trend: '+12%', trendColor: 'text-green-500' },
    { label: 'B2B Partners', value: '18', trend: null },
    { label: 'Monthly Revenue', value: '£214k', trend: '+8.4%', trendColor: 'text-green-500' },
    { label: 'Properties / Units', value: '12 props · 486 units', trend: null },
    { label: 'Open Maintenance Requests', value: '7', trend: 'Amber', trendColor: 'text-amber-500' },
    { label: 'Pending Applications', value: '14', trend: 'Amber', trendColor: 'text-amber-500' },
  ],
  revenue: [
    { month: 'Apr \'24', b2c: 85000, b2b: 42000 },
    { month: 'May \'24', b2c: 92000, b2b: 45000 },
    { month: 'Jun \'24', b2c: 88000, b2b: 48000 },
    { month: 'Jul \'24', b2c: 95000, b2b: 52000 },
    { month: 'Aug \'24', b2c: 102000, b2b: 55000 },
    { month: 'Sep \'24', b2c: 98000, b2b: 58000 },
    { month: 'Oct \'24', b2c: 105000, b2b: 62000 },
    { month: 'Nov \'24', b2c: 112000, b2b: 65000 },
    { month: 'Dec \'24', b2c: 108000, b2b: 68000 },
    { month: 'Jan \'25', b2c: 115000, b2b: 72000 },
    { month: 'Feb \'25', b2c: 122000, b2b: 75000 },
    { month: 'Mar \'25', b2c: 128000, b2b: 86000 },
  ],
  occupancy: [
    { city: 'Aachen', rate: 84 },
    { city: 'Berlin', rate: 92 },
    { city: 'Bonn', rate: 78 },
    { city: 'Cologne', rate: 88 },
    { city: 'Dusseldorf', rate: 81 },
    { city: 'Frankfurt', rate: 95 },
    { city: 'Hamburg', rate: 89 },
    { city: 'Munich', rate: 94 },
  ],
  tenants: [
    { country: 'India', count: 45 },
    { country: 'Nigeria', count: 32 },
    { country: 'Brazil', count: 28 },
    { country: 'Germany', count: 25 },
    { country: 'United Arab Emirates', count: 22 },
    { country: 'USA', count: 20 },
    { country: 'UK', count: 18 },
    { country: 'France', count: 15 },
    { country: 'Canada', count: 12 },
    { country: 'Netherlands', count: 10 },
    { country: 'Spain', count: 8 },
    { country: 'Italy', count: 7 },
    { country: 'China', count: 6 },
    { country: 'Japan', count: 5 },
    { country: 'South Africa', count: 4 },
  ],
  properties: [
    { city: 'London', coordinates: [-0.1278, 51.5074], count: 3 },
    { city: 'Berlin', coordinates: [13.4050, 52.5200], count: 2 },
    { city: 'Amsterdam', coordinates: [4.9041, 52.3676], count: 3 },
    { city: 'Dubai', coordinates: [55.2708, 25.2048], count: 2 },
    { city: 'Lisbon', coordinates: [-9.1393, 38.7223], count: 2 },
    { city: 'Aachen', coordinates: [6.0839, 50.7753], count: 1 },
    { city: 'Bonn', coordinates: [7.0982, 50.7339], count: 1 },
    { city: 'Cologne', coordinates: [6.9583, 50.9375], count: 2 },
    { city: 'Dusseldorf', coordinates: [6.7735, 51.2277], count: 1 },
    { city: 'Frankfurt', coordinates: [8.6821, 50.1109], count: 2 },
    { city: 'Hamburg', coordinates: [9.9937, 53.5511], count: 1 },
    { city: 'Munich', coordinates: [11.5820, 48.1351], count: 2 },
  ],
  funnel: [
    { stage: 'Submitted', count: 120, conversion: '100%' },
    { stage: 'In Review', count: 84, conversion: '70%' },
    { stage: 'Approved', count: 56, conversion: '66%' },
    { stage: 'Signed', count: 42, conversion: '75%' },
    { stage: 'Moved In', count: 38, conversion: '90%' },
  ],
  activity: [
    { type: 'success', text: 'Application approved — Priya Nair, Studio LDN', time: '2m ago' },
    { type: 'warning', text: 'Role changed — ops@arrivio.com → Ops Manager', time: '1h ago' },
    { type: 'info', text: 'Invoice generated — Accenture Ltd #1043', time: '3h ago' },
    { type: 'error', text: 'Application rejected — Marco Silva, 1BR BER', time: '5h ago' },
    { type: 'success', text: 'DocuSign countersigned — Tomás Bravo', time: '6h ago' },
    { type: 'info', text: 'New partner onboarded — Wipro Technologies', time: '8h ago' },
  ],
  health: [
    { service: 'Stripe', status: 'Connected', color: 'bg-green-50 text-green-800' },
    { service: 'DocuSign', status: 'Connected', color: 'bg-green-50 text-green-800' },
    { service: 'Email service', status: 'Healthy', color: 'bg-green-50 text-green-800' },
    { service: 'Webhooks', status: 'Firing', color: 'bg-green-50 text-green-800' },
  ],
  actions: [
    { label: 'Unsigned agreements', badge: '6 pending', color: 'bg-red-50 text-red-800' },
    { label: 'Applications over 3 days old', badge: '4 stale', color: 'bg-amber-50 text-amber-800' },
    { label: 'Overdue B2B invoices', badge: '3 overdue', color: 'bg-red-50 text-red-800' },
    { label: 'Flagged community posts', badge: '2 flagged', color: 'bg-amber-50 text-amber-800' },
  ],
  portfolioSnapshot: [
    { label: 'Avg occupancy across all properties', value: '91%', trend: 'up', status: 'green' },
    { label: 'B2B capacity fill rate', value: '78%', trend: 'down', status: 'amber' },
    { label: 'Tenants with leases expiring < 30 days', value: '8', status: 'amber' },
    { label: 'Commission payouts due this week', value: '£12,400', status: 'amber' },
    { label: 'New partner applications pending', value: '2', status: 'amber' },
    { label: 'Longest unresolved support case', value: '4 days', status: 'red' },
  ],
};
