const annualRevenue = 19679179;
const monthlyRunRate = 1639932;

export const dashboardData = {
  metrics: [
    { label: 'Annual Revenue', value: '€19,679,179' },
    { label: 'Monthly Run-Rate', value: '€1,639,932' },
    { label: 'Gross Margin', value: '47.8%' },
    { label: 'Annual EBITDA', value: '€5,865,482' },
    { label: 'EBITDA Margin', value: '26.8%' },
    { label: 'Rooms Under Management', value: '3,120' },
    { label: 'Portfolio Occupancy', value: '96%' },
    { label: 'Community Buildings', value: '16' },
    { label: 'Apartments Leased', value: '240' },
    { label: 'B2B Partners', value: '47' },
    { label: 'Team Size', value: '21 FTE' },
  ],
  revenue: {
    summaryAnnualRevenue: annualRevenue,
    summaryMonthlyRevenue: monthlyRunRate,
    points: [
      { period: 'Q5 FY27', b2b: 1174000, b2c: 1080000, services: 200000 },
      { period: 'Q6 FY27', b2b: 2514000, b2c: 1230000, services: 310000 },
      { period: 'Q7 FY28', b2b: 3844000, b2c: 1380000, services: 430000 },
      { period: 'Q8 FY28', b2b: 5090959, b2c: 1556078, services: 606142 },
    ],
  },
  occupancy: [
    { city: 'Düsseldorf', rate: 97 },
    { city: 'Cologne', rate: 96 },
    { city: 'Bonn', rate: 96 },
    { city: 'Aachen', rate: 96 },
    { city: 'Berlin', rate: 96 },
    { city: 'Frankfurt', rate: 97 },
    { city: 'Munich', rate: 95 },
    { city: 'Hamburg', rate: 95 },
  ],
  tenants: [
    { country: 'India', count: 712 },
    { country: 'Philippines', count: 408 },
    { country: 'Poland', count: 286 },
    { country: 'Spain', count: 241 },
    { country: 'Nigeria', count: 198 },
    { country: 'Turkey', count: 177 },
    { country: 'Romania', count: 165 },
    { country: 'Germany', count: 144 },
    { country: 'Portugal', count: 126 },
    { country: 'Italy', count: 109 },
  ],
  properties: [
    { city: 'Düsseldorf', coordinates: [6.7735, 51.2277], count: 4 },
    { city: 'Cologne', coordinates: [6.9583, 50.9375], count: 3 },
    { city: 'Bonn', coordinates: [7.0982, 50.7374], count: 2 },
    { city: 'Aachen', coordinates: [6.0839, 50.7753], count: 1 },
    { city: 'Berlin', coordinates: [13.405, 52.52], count: 3 },
    { city: 'Frankfurt', coordinates: [8.6821, 50.1109], count: 1 },
    { city: 'Munich', coordinates: [11.582, 48.1351], count: 2 },
    { city: 'Hamburg', coordinates: [9.9937, 53.5511], count: 1 },
  ],
  funnel: [
    { stage: 'Employer Commitments', count: 520 },
    { stage: 'Housing Confirmed', count: 442 },
    { stage: 'Move-in Scheduled', count: 312 },
    { stage: 'Lease Active', count: 287 },
  ],
  activity: [
    { type: 'success', text: 'Klinikum Düsseldorf committed 12 additional rooms in Flingern.', time: '12m ago' },
    { type: 'info', text: 'Arrivio Berlin Neukölln reached 96% stabilized occupancy.', time: '38m ago' },
    { type: 'success', text: 'Heinrich-Heine-Universität autumn intake housing list locked.', time: '1h ago' },
    { type: 'warning', text: 'University semester invoice batch pending approval for €21,400.', time: '2h ago' },
    { type: 'info', text: 'Düsseldorf apartment portfolio held 96% occupancy this month.', time: '3h ago' },
    { type: 'success', text: 'Maintenance buffer rebalanced to 33 rooms across live buildings.', time: '5h ago' },
  ],
  health: [
    { service: 'Stripe', status: 'Connected', color: 'bg-green-50 text-green-800' },
    { service: 'DocuSign', status: 'Connected', color: 'bg-green-50 text-green-800' },
    { service: 'Email Service', status: 'Healthy', color: 'bg-green-50 text-green-800' },
    { service: 'B2B Portal', status: 'Healthy', color: 'bg-green-50 text-green-800' },
  ],
  actions: [
    { label: 'Employer move-ins awaiting visa clearance', badge: '4 records', color: 'bg-amber-50 text-amber-800' },
    { label: 'Pending service fees ready for reconciliation', badge: '€127,400', color: 'bg-red-50 text-red-800' },
    { label: 'Late-stage Wave 2 buildings completing handover this quarter', badge: '3 assets', color: 'bg-emerald-50 text-emerald-800' },
    { label: 'Investor conversion note archived as equity event', badge: '1 update', color: 'bg-emerald-50 text-emerald-800' },
  ],
  portfolioSnapshot: [
    { label: 'Occupied rooms across the portfolio', value: '2,995', status: 'green' },
    { label: 'B2B housing revenue share', value: '64%', status: 'green' },
    { label: 'Pending service fees outstanding', value: '€127,400', status: 'amber' },
    { label: 'Available for immediate placement', value: '~125 rooms', status: 'green' },
    { label: 'Investor seed note status', value: 'Converted to Equity', status: 'green' },
    { label: 'Wave 2 live building occupancy band', value: '94-96%', status: 'green' },
  ],
};
