import {
  LayoutDashboard,
  FileText,
  Building2,
  DollarSign,
  Users,
  BarChart3,
  Settings,
  Building,
  UserCheck,
  FileSignature,
} from 'lucide-react';

export const navConfig = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    route: '/admin/dashboard',
    roles: ['super_admin', 'ops_manager', 'sales_partnership', 'finance_manager', 'support_agent', 'community_manager'],
    subs: [],
  },
  {
    id: 'b2c',
    label: 'B2C Applications',
    icon: FileText,
    route: '/admin/b2c',
    roles: ['super_admin', 'ops_manager', 'support_agent'],
    subs: [
      { id: 'b2c_applications',  label: 'All Applications',    route: '/admin/b2c/applications', badgeKey: 'pending_b2c', roles: ['super_admin', 'ops_manager', 'support_agent'] },
      { id: 'b2c_documents',     label: 'Documents',           route: '/admin/b2c/documents',    badgeKey: 'pending_docs', roles: ['super_admin', 'ops_manager'] },
      { id: 'b2c_units',         label: 'Properties & Units',  route: '/admin/b2c/properties',   roles: ['super_admin', 'ops_manager'] },
      { id: 'b2c_move',          label: 'Move-ins / Move-outs',route: '/admin/b2c/move',         roles: ['super_admin', 'ops_manager'] },
      { id: 'b2c_waitlist',      label: 'Waitlist',            route: '/admin/b2c/waitlist',     roles: ['super_admin', 'ops_manager', 'support_agent'] },
    ],
  },
  {
    id: 'b2b',
    label: 'B2B Partners',
    icon: Building2,
    route: '/admin/b2b',
    roles: ['super_admin', 'ops_manager', 'sales_partnership', 'finance_manager', 'support_agent'],
    subs: [
      { id: 'b2b_partners', label: 'All Partners', route: '/admin/b2b/partners', roles: ['super_admin', 'ops_manager', 'sales_partnership'] },
      { id: 'b2b_capacity', label: 'Capacity Reservations', route: '/admin/b2b/capacity', roles: ['super_admin', 'ops_manager', 'sales_partnership'] },
      { id: 'b2b_employees', label: 'Employee Tracker', route: '/admin/b2b/employees', roles: ['super_admin', 'ops_manager', 'sales_partnership'] },
      { id: 'b2b_comms', label: 'Communications', route: '/admin/b2b/comms', roles: ['super_admin', 'sales_partnership', 'support_agent'] },
      { id: 'b2b_service_fees', label: 'Service Fees', route: '/admin/b2b/service-fees', roles: ['super_admin', 'sales_partnership', 'finance_manager'] },
    ],
  },
  {
    id: 'contracts',
    label: 'Contracts',
    icon: FileSignature,
    route: '/admin/contracts',
    roles: ['super_admin', 'ops_manager', 'sales_partnership', 'finance_manager', 'support_agent', 'community_manager'],
    subs: [],
  },
  {
    id: 'tenants',
    label: 'Tenants',
    icon: UserCheck,
    route: '/admin/tenants',
    roles: ['super_admin', 'ops_manager', 'support_agent', 'community_manager'],
    subs: [
      { id: 'tenants_all',     label: 'All Tenants',   route: '/admin/tenants/all',   roles: ['super_admin', 'ops_manager', 'support_agent'] },
      { id: 'tenants_b2b',     label: 'B2B Companies', route: '/admin/tenants/b2b',   roles: ['super_admin', 'ops_manager'] },
      { id: 'tenants_leases',  label: 'Leases',        route: '/admin/tenants/leases',roles: ['super_admin', 'ops_manager'] },
      { id: 'tenants_ledger',  label: 'Rent Ledger',   route: '/admin/tenants/ledger',roles: ['super_admin', 'finance_manager'] },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icon: DollarSign,
    route: '/admin/finance',
    roles: ['super_admin', 'finance_manager'],
    subs: [
      { id: 'finance_payments', label: 'B2C Payments', route: '/admin/finance/payments', roles: ['super_admin', 'finance_manager'] },
      { id: 'finance_invoices', label: 'B2B Invoices', route: '/admin/finance/invoices', roles: ['super_admin', 'finance_manager'] },
      { id: 'finance_refunds', label: 'Refunds', route: '/admin/finance/refunds', roles: ['super_admin', 'finance_manager'] },
      { id: 'finance_deposits', label: 'Security Deposits', route: '/admin/finance/deposits', roles: ['super_admin', 'finance_manager'] },
      { id: 'finance_pricing', label: 'Pricing Rules', route: '/admin/finance/pricing', roles: ['super_admin', 'finance_manager'] },
    ],
  },
  {
    id: 'properties',
    label: 'Properties & Cities',
    icon: Building,
    route: '/admin/properties',
    roles: ['super_admin', 'ops_manager'],
    subs: [
      { id: 'properties_all',       label: 'All Properties', route: '/admin/properties/list',          roles: ['super_admin', 'ops_manager'] },
      { id: 'properties_cities',    label: 'City Manager',   route: '/admin/properties/cities',   roles: ['super_admin', 'ops_manager'] },
      { id: 'properties_types',     label: 'Unit Types',     route: '/admin/properties/types',    roles: ['super_admin', 'ops_manager'] },
      { id: 'properties_amenities', label: 'Amenities',      route: '/admin/properties/amenities',roles: ['super_admin', 'ops_manager'] },
    ],
  },
  {
    id: 'community',
    label: 'Community',
    icon: Users,
    roles: ['super_admin', 'community_manager', 'ops_manager'],
    subs: [
      { id: 'community_events', label: 'Events', route: '/admin/community/events', roles: ['super_admin', 'community_manager'] },
      { id: 'community_clubs', label: 'Clubs', route: '/admin/community/clubs', roles: ['super_admin', 'community_manager'] },
      { id: 'community_announcements', label: 'Announcements', route: '/admin/community/announcements', roles: ['super_admin', 'community_manager', 'ops_manager'] },
      { id: 'community_feed', label: 'Feed Moderation', route: '/admin/community/feed', roles: ['super_admin', 'community_manager'] },
      { id: 'community_push', label: 'Push Notifications', route: '/admin/community/push', roles: ['super_admin', 'community_manager'] },
      { id: 'community_residents', label: 'Resident Directory', route: '/admin/community/residents', roles: ['super_admin', 'community_manager'] },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: BarChart3,
    roles: ['super_admin', 'ops_manager', 'finance_manager'],
    subs: [
      { id: 'reports_occupancy', label: 'Occupancy', route: '/admin/reports/occupancy', roles: ['super_admin', 'ops_manager'] },
      { id: 'reports_funnel', label: 'Application Funnel', route: '/admin/reports/funnel', roles: ['super_admin', 'ops_manager'] },
      { id: 'reports_revenue', label: 'Revenue', route: '/admin/reports/revenue', roles: ['super_admin', 'finance_manager'] },
      { id: 'reports_leads', label: 'Lead Source', route: '/admin/reports/leads', roles: ['super_admin', 'ops_manager'] },
      { id: 'reports_leases', label: 'Lease Expiry Forecast', route: '/admin/reports/leases', roles: ['super_admin', 'ops_manager'] },
      { id: 'reports_b2b', label: 'B2B Performance', route: '/admin/reports/b2b', roles: ['super_admin', 'finance_manager'] },
      { id: 'reports_community', label: 'Community Engagement', route: '/admin/reports/community', roles: ['super_admin'] },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings,
    roles: ['super_admin'],
    subs: [
      { id: 'settings_admins', label: 'Admin Accounts', route: '/admin/settings/admins', roles: ['super_admin'] },
      { id: 'settings_roles', label: 'Roles & Permissions', route: '/admin/settings/roles', roles: ['super_admin'] },
      { id: 'settings_audit', label: 'Audit Log', route: '/admin/settings/audit', roles: ['super_admin'] },
      { id: 'settings_email', label: 'Email Templates', route: '/admin/settings/email', roles: ['super_admin'] },
      { id: 'settings_docusign', label: 'DocuSign Config', route: '/admin/settings/docusign', roles: ['super_admin'] },
      { id: 'settings_stripe', label: 'Stripe Config', route: '/admin/settings/stripe', roles: ['super_admin'] },
      { id: 'settings_flags', label: 'Feature Flags', route: '/admin/settings/flags', roles: ['super_admin'] },
    ],
  },
];
